//go:build !ignore_autogenerated

/*
Copyright 2024 The Elara Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUTHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElaraPolicy) DeepCopyInto(out *ElaraPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElaraPolicy.
func (in *ElaraPolicy) DeepCopy() *ElaraPolicy {
	if in == nil {
		return nil
	}
	out := new(ElaraPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElaraPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElaraPolicyList) DeepCopyInto(out *ElaraPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ElaraPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElaraPolicyList.
func (in *ElaraPolicyList) DeepCopy() *ElaraPolicyList {
	if in == nil {
		return nil
	}
	out := new(ElaraPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElaraPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElaraPolicySpec) DeepCopyInto(out *ElaraPolicySpec) {
	*out = *in
	if in.Deployments != nil {
		in, out := &in.Deployments, &out.Deployments
		*out = make([]ManagedDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElaraPolicySpec.
func (in *ElaraPolicySpec) DeepCopy() *ElaraPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ElaraPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElaraPolicyStatus) DeepCopyInto(out *ElaraPolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElaraPolicyStatus.
func (in *ElaraPolicyStatus) DeepCopy() *ElaraPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ElaraPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedDeployment) DeepCopyInto(out *ManagedDeployment) {
	*out = *in
	out.Weight = in.Weight.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedDeployment.
func (in *ManagedDeployment) DeepCopy() *ManagedDeployment {
	if in == nil {
		return nil
	}
	out := new(ManagedDeployment)
	in.DeepCopyInto(out)
	return out
}
