//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentGroupSpec) DeepCopyInto(out *DeploymentGroupSpec) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]GroupMemberSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentGroupSpec.
func (in *DeploymentGroupSpec) DeepCopy() *DeploymentGroupSpec {
	if in == nil {
		return nil
	}
	out := new(DeploymentGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentTargetSpec) DeepCopyInto(out *DeploymentTargetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentTargetSpec.
func (in *DeploymentTargetSpec) DeepCopy() *DeploymentTargetSpec {
	if in == nil {
		return nil
	}
	out := new(DeploymentTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElaraScaler) DeepCopyInto(out *ElaraScaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElaraScaler.
func (in *ElaraScaler) DeepCopy() *ElaraScaler {
	if in == nil {
		return nil
	}
	out := new(ElaraScaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElaraScaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElaraScalerList) DeepCopyInto(out *ElaraScalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ElaraScaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElaraScalerList.
func (in *ElaraScalerList) DeepCopy() *ElaraScalerList {
	if in == nil {
		return nil
	}
	out := new(ElaraScalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElaraScalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElaraScalerSpec) DeepCopyInto(out *ElaraScalerSpec) {
	*out = *in
	out.Deadband = in.Deadband.DeepCopy()
	in.StabilizationWindow.DeepCopyInto(&out.StabilizationWindow)
	if in.DeploymentGroups != nil {
		in, out := &in.DeploymentGroups, &out.DeploymentGroups
		*out = make([]DeploymentGroupSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IndependentDeployments != nil {
		in, out := &in.IndependentDeployments, &out.IndependentDeployments
		*out = make([]IndependentDeploymentSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElaraScalerSpec.
func (in *ElaraScalerSpec) DeepCopy() *ElaraScalerSpec {
	if in == nil {
		return nil
	}
	out := new(ElaraScalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElaraScalerStatus) DeepCopyInto(out *ElaraScalerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ReferencePower != nil {
		in, out := &in.ReferencePower, &out.ReferencePower
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.TriggerTime != nil {
		in, out := &in.TriggerTime, &out.TriggerTime
		*out = (*in).DeepCopy()
	}
	if in.TriggerPower != nil {
		in, out := &in.TriggerPower, &out.TriggerPower
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.LastScaleTime != nil {
		in, out := &in.LastScaleTime, &out.LastScaleTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElaraScalerStatus.
func (in *ElaraScalerStatus) DeepCopy() *ElaraScalerStatus {
	if in == nil {
		return nil
	}
	out := new(ElaraScalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupMemberSpec) DeepCopyInto(out *GroupMemberSpec) {
	*out = *in
	out.DeploymentTargetSpec = in.DeploymentTargetSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupMemberSpec.
func (in *GroupMemberSpec) DeepCopy() *GroupMemberSpec {
	if in == nil {
		return nil
	}
	out := new(GroupMemberSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndependentDeploymentSpec) DeepCopyInto(out *IndependentDeploymentSpec) {
	*out = *in
	out.DeploymentTargetSpec = in.DeploymentTargetSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndependentDeploymentSpec.
func (in *IndependentDeploymentSpec) DeepCopy() *IndependentDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(IndependentDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StabilizationWindowSpec) DeepCopyInto(out *StabilizationWindowSpec) {
	*out = *in
	out.Increase = in.Increase
	out.Decrease = in.Decrease
	out.IncreaseTolerance = in.IncreaseTolerance.DeepCopy()
	out.DecreaseTolerance = in.DecreaseTolerance.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StabilizationWindowSpec.
func (in *StabilizationWindowSpec) DeepCopy() *StabilizationWindowSpec {
	if in == nil {
		return nil
	}
	out := new(StabilizationWindowSpec)
	in.DeepCopyInto(out)
	return out
}
